apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-v1
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-job-container
              image: devopsacr.azurecr.io/cron-job:v1
              args:
                - /bin/sh
                - -c
                - "echo Running CronJob v1 from Azure ACR!"
          restartPolicy: OnFailure
